### ISSUE TITLE
Receive Unexpected runtime exception when registering a service.

### ISSUE THREAD

**Issue by gonzalovazquez** [networknt/light-oauth2#21]
Hi Steve,

I receive an Unexpected runtime exception when I am running light-oauth2 docker-compose-oracle.yml. It does not happen with the SQL version. I have only been able to reproduce it with oracle. 

Here is my POST request: 
```
curl --request POST \
  --url http://localhost:6883/oauth2/service \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/json' \
  --data '{\n"serviceId":"MRKT0002",\n"serviceType":"api",\n"serviceName":"Retail Account",\n"serviceDesc":"Microservices for Marketplace Account",\n"scope":"mrk.r",\n"ownerId":"admin"\n}'
```

To reproduce please use the version from master and docker-compose-oracle.yml

Thanks,
Gonzalo

**Comment by stevehu** [comment]
It must be script error in Oracle. I am building it with 1.2.4 to reproduce it. Thanks.

**Comment by stevehu** [comment]
It looks like the body is not an valid json and body parser throws exception. Could you please try the following curl command with all the '\n' removed. 

```
curl --request POST --url http://localhost:6883/oauth2/service --header 'cache-control: no-cache' --header 'content-type: application/json' --data '{"serviceId":"MRKT0002","serviceType":"api","serviceName":"Retail Account","serviceDesc":"Microservices for Marketplace Account","scope":"mrk.r","ownerId":"admin"}'
```

Here is the error message I got. 

```
oauth2-service_1        | 14:22:50.511 [XNIO-1 task-2] M9y2b83ISmWo2VbnP6tFnw ERROR com.networknt.body.BodyHandler - IOException: 
oauth2-service_1        | com.fasterxml.jackson.core.JsonParseException: Unexpected character ('\' (code 92)): was expecting double-quote to start field name
oauth2-service_1        |  at [Source: {\n"serviceId":"MRKT0002",\n"serviceType":"api",\n"serviceName":"Retail Account",\n"serviceDesc":"Microservices for Marketplace Account",\n"scope":"mrk.r",\n"ownerId":"admin"\n}; line: 1, column: 3]
oauth2-service_1        | 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
oauth2-service_1        | 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
oauth2-service_1        | 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
oauth2-service_1        | 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1767)
oauth2-service_1        | 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:921)
oauth2-service_1        | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:483)
oauth2-service_1        | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:352)
oauth2-service_1        | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
oauth2-service_1        | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
oauth2-service_1        | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2852)
oauth2-service_1        | 	at com.networknt.body.BodyHandler.handleRequest(BodyHandler.java:81)
oauth2-service_1        | 	at com.networknt.swagger.SwaggerHandler.handleRequest(SwaggerHandler.java:92)
oauth2-service_1        | 	at com.networknt.cors.CorsHttpHandler.handleRequest(CorsHttpHandler.java:81)
oauth2-service_1        | 	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:67)
oauth2-service_1        | 	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:64)
oauth2-service_1        | 	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:62)
oauth2-service_1        | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
oauth2-service_1        | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
oauth2-service_1        | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
oauth2-service_1        | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
oauth2-service_1        | 	at java.lang.Thread.run(Thread.java:745)

```

**Comment by stevehu** [comment]
From the database result, I did find an issue with the createDt not populated in the get request result. I will create another issue to get it fixed. Thanks a lot for your help.

```
curl http://localhost:6883/oauth2/service?page=1
```
result
```
[{"serviceId":"AACT0001","serviceType":"ms","serviceName":"Account Service","serviceDesc":"A microservice that serves account information","ownerId":"admin","scope":"a.r b.r","createDt":"2017-02-20","updateDt":null},{"serviceId":"MRKT0002","serviceType":"api","serviceName":"Retail Account","serviceDesc":"Microservices for Marketplace Account","ownerId":"admin","scope":"mrk.r","createDt":null,"updateDt":null}]
```
