### ISSUE TITLE
Unrecognized field authenticateClass not marked as ignorable

### ISSUE THREAD

**Issue by stevehu** [networknt/light-oauth2#81]
This is an reserved field in database and should not be mandatory. 

```
oauth2-client_1         | 21:23:31.412 [XNIO-1 task-12]  0QPlT1aEQgqaic5ivN_q1w ERROR c.n.exception.ExceptionHandler handleRequest - Exception:
oauth2-client_1         | java.lang.IllegalArgumentException: Unrecognized field "authenticateClass" (class com.networknt.oauth.cache.model.Client), not marked as ignorable (12 known properties: "redirectUri", "scope", "clientType", "clientId", "updateDt", "clientSecret", "clientDesc", "clientProfile", "clientName", "customClaim", "createDt", "ownerId"])
oauth2-client_1         |  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.networknt.oauth.cache.model.Client["authenticateClass"])
oauth2-client_1         | 	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3738)
oauth2-client_1         | 	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3656)
oauth2-client_1         | 	at com.networknt.oauth.client.handler.Oauth2ClientPutHandler.handleRequest(Oauth2ClientPutHandler.java:27)
oauth2-client_1         | 	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
oauth2-client_1         | 	at com.networknt.validator.ValidatorHandler.handleRequest(ValidatorHandler.java:82)
oauth2-client_1         | 	at com.networknt.sanitizer.SanitizerHandler.handleRequest(SanitizerHandler.java:87)
oauth2-client_1         | 	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:150)
oauth2-client_1         | 	at com.networknt.body.BodyHandler.handleRequest(BodyHandler.java:115)
oauth2-client_1         | 	at com.networknt.swagger.SwaggerHandler.handleRequest(SwaggerHandler.java:95)
oauth2-client_1         | 	at com.networknt.cors.CorsHttpHandler.handleRequest(CorsHttpHandler.java:73)
oauth2-client_1         | 	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:70)
oauth2-client_1         | 	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:64)
oauth2-client_1         | 	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:72)
oauth2-client_1         | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
oauth2-client_1         | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
oauth2-client_1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
oauth2-client_1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
oauth2-client_1         | 	at java.lang.Thread.run(Thread.java:748)
oauth2-client_1         | Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "authenticateClass" (class com.networknt.oauth.cache.model.Client), not marked as ignorable (12 known properties: "redirectUri", "scope", "clientType", "clientId", "updateDt", "clientSecret", "clientDesc", "clientProfile", "clientName", "customClaim", "createDt", "ownerId"])
oauth2-client_1         |  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.networknt.oauth.cache.model.Client["authenticateClass"])
oauth2-client_1         | 	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
oauth2-client_1         | 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
oauth2-client_1         | 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
oauth2-client_1         | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1582)
oauth2-client_1         | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1560)
oauth2-client_1         | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
oauth2-client_1         | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
oauth2-client_1         | 	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3733)
oauth2-client_1         | 	... 17 common frames omitted
oauth2-client_1         | 21:23:42.497 [XNIO-1 task-15]  IyCe-JDdSJqHGJ4pF9ujeg ERROR c.n.exception.ExceptionHandler handleRequest - Exception:
oauth2-client_1         | java.lang.IllegalArgumentException: Unrecognized field "authenticateClass" (class com.networknt.oauth.cache.model.Client), not marked as ignorable (12 known properties: "redirectUri", "scope", "clientType", "clientId", "updateDt", "clientSecret", "clientDesc", "clientProfile", "clientName", "customClaim", "createDt", "ownerId"])
oauth2-client_1         |  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.networknt.oauth.cache.model.Client["authenticateClass"])
oauth2-client_1         | 	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3738)
oauth2-client_1         | 	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3656)
oauth2-client_1         | 	at com.networknt.oauth.client.handler.Oauth2ClientPutHandler.handleRequest(Oauth2ClientPutHandler.java:27)
oauth2-client_1         | 	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
oauth2-client_1         | 	at com.networknt.validator.ValidatorHandler.handleRequest(ValidatorHandler.java:82)
oauth2-client_1         | 	at com.networknt.sanitizer.SanitizerHandler.handleRequest(SanitizerHandler.java:87)
oauth2-client_1         | 	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:150)
oauth2-client_1         | 	at com.networknt.body.BodyHandler.handleRequest(BodyHandler.java:115)
oauth2-client_1         | 	at com.networknt.swagger.SwaggerHandler.handleRequest(SwaggerHandler.java:95)
oauth2-client_1         | 	at com.networknt.cors.CorsHttpHandler.handleRequest(CorsHttpHandler.java:73)
oauth2-client_1         | 	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:70)
oauth2-client_1         | 	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:64)
oauth2-client_1         | 	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:72)
oauth2-client_1         | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
oauth2-client_1         | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
oauth2-client_1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
oauth2-client_1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
oauth2-client_1         | 	at java.lang.Thread.run(Thread.java:748)
oauth2-client_1         | Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "authenticateClass" (class com.networknt.oauth.cache.model.Client), not marked as ignorable (12 known properties: "redirectUri", "scope", "clientType", "clientId", "updateDt", "clientSecret", "clientDesc", "clientProfile", "clientName", "customClaim", "createDt", "ownerId"])

```

**Comment by stevehu** [comment]
This ends up the documentation issue in the light-oauth2 tutorial.
